language: ruby

rvm:
- 2.5.3

script: "./script/cibuild"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

notifications:
  slack:
    rooms:
      secure: DZzJIgmCuHZMecqUE1VJWUCSTLctJuYJq6KxDDipaSVw1u429/BQhsuxkrJ7Ft6V4HFZmq2N7bZpLa3wQvgViyK1xsF8/XUBkubfIFDyK/ZHNoyFEDRzYkGmk4iiGwUmtaHquhWoDg23BrBiUinisRH7DP+OULYQBJ/Uvzxi+Jco3ZMI15Cd29TYTZwcGqVCw5lEZpdvWiWzCi+kEL7OdO8v/y0A40wMxDIsLEy5O+3JWQP+y3kXPpaficRCVjyilirDo0DmEC423za3LqXDfqZV5Arevszly36WfDnBAp0HhyWcDqye1KZDkVHQgSjGaNDKpL0wR2D7C4XU8amlIKPSEM64jSVPbmx1Ft0w+QMHS3mx9udm9jO+JYXM8KAbBkTxK4j/nVcZaASD36sSui8kcinLEWarb8s0UHLmbWdA5/hB8VxAjHTgfFAYo3cvSIDlT3/UpR/O6EpEwe8XIol2pIWZOpAyvDqXNMJE+EZQY8fOEnph51YKgS7b8d95F5MQgmkkmiZb7IEEClmhkMMXa+Snon42V5QkdZINg+5TZv7HAoBRLlWgziAlH3FOXzVuf0KACiFVvUqBLprVKW9w0s9A6tpYuBBib1wA0bAkYC11XMYSrgDFQRmO7z7GyGR/Pxhd4d0oVQSpuIyyj21yiQKM6AKKDL/pZAdLkAI=
