backend:
  name: git-gateway
  branch: master
display_url: https://catalog.docnow.io/
site_url: https://catalog.docnow.io/
logo_url: https://catalog.docnow.io/images/docnow.png
media_folder: static/images
public_folder: /images

collections:
  - name: datasets
    label: Datasets
    identifier_field: title
    folder: src/datasets
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
        hint: The title for your dataset.
      - label: Dataset URL
        name: url
        widget: string
        pattern:
          - https?://.+
          - Must be a URL
        hint: The URL for where your dataset has been published.
      - label: Repository
        name: repository
        widget: string
        hint: The name of the repository where your dataset has been published.
      - label: Number of Tweets
        name: tweets
        widget: number
        hint: The total number of tweets in your dataset.
      - label: Creators
        name: creators
        widget: list
        collapsed: false
        hint: Names and optional email addresses for the creators of the dataset.
        fields: 
          - label: Name
            name: name
            widget: string
          - label: Email
            name: email
            widget: string
            required: false
      - label: Tweet Dates
        name: dates
        widget: list
        required: true
        collapsed: false
        hint: The date coverage for the tweets in your dataset.
        fields:
          - label: Start
            name: start
            widget: date
            required: true
          - label: End
            name: end
            widget: date
            required: true
      - label: Date Published
        name: published
        widget: datetime
        hint: When the dataset was published in the repository.
      - label: Date Added
        name: added
        widget: datetime
        hint: The date this Catalog record will be published.
      - label: Subjects
        name: subjects
        widget: list
        collapsed: false
        hint: A list of subject terms for the contents of your datasets.
        field: 
          label: Subject
          name: subject
          widget: string
      - label: Description
        name: body
        widget: markdown
        hint: Please provide a description of how and why you created your dataset. Think about what kind of description will help researchers use your dataset.
      - label: Public Notification 
        name: notification
        widget: text
        hint: Did you publicly share (on Twitter) that you were collecting this content?
        required: true
      - label: Opt-Out?
        name: optout
        widget: text
        hint:  Do content creators have the option to opt out of your collecting or remove their content after collection has taken place?
        required: true
      - label: Contact?
        name: contact
        widget: text
        hint: Do you have an easy-to-find way for content creators to reach out to you or your organization about your collecting project?
        required: true
      - label: Analyzed Threats?
        name: threat
        widget: text
        hint: Have you analyzed the tweet dataset for potential threats to those whose content has been collected?
        required: true
      - label: Collection Development?
        name: collecting
        widget: text
        hint: Is this tweet dataset part of a larger collecting effort of topical materials, including oral histories, web archiving, or physical materials?
        required: true